# Generated by Django 4.1.5 on 2023-01-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='book_price',
        ),
    ]
