# Generated by Django 4.1.5 on 2023-01-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_rename_price_book_book_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
