# Generated by Django 4.1.5 on 2023-01-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_book_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
